### ISSUE TITLE
Artstation jQuery getJson from url

### ISSUE THREAD

**Issue by oytundd** [AliCormack/InspiringNewTab#1]
Hello i have my own little extension that i am working on for couple of days only using Artstation but when i try to use jQuery getjson(); function i just get a "blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource." error. I have looked through your code but i could not find anything related to headers. How were you be able to solve this problem?

**Comment by Pustur** [comment]
I don't know for sure but I bet it has something to do with this line:

https://github.com/AliCormack/InspiringNewTab/blob/26d304ba1e79ac6c8513ca753da39ba7ded27c2a/manifest.json#L21

Documentation: [content_security_policy](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_security_policy)

**Comment by oytundd** [comment]
> I don't know for sure but I bet it has something to do with this line:
> 
> https://github.com/AliCormack/InspiringNewTab/blob/26d304ba1e79ac6c8513ca753da39ba7ded27c2a/manifest.json#L21
> 
> Documentation: [content_security_policy](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_security_policy)

I am not really familiar with extensions and i did not really think to check the manifest, adding that line and the content_scripts part fixed my problem. Thank you!
